package com.awscontact.model;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "CONTACT")
public class Contact implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	// ------------------------
	// PRIVATE FIELDS
	// ------------------------
	// An autogenerated id (unique for each user in the db)
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private long id;
	private String name;
	private String email;
	private String profession;

	public Contact() {
		super();
	}

	public Contact(long id, String name, String email, String profession) {
		super();
		this.id = id;
		this.name = name;
		this.email = email;
		this.profession = profession;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getProfession() {
		return profession;
	}

	public void setProfession(String profession) {
		this.profession = profession;
	}


    @Override
    public String toString() {
        return "Contact{" +
                "id=" + id +
                ", username='" + name + '\'' +
                ", email='" + email +'\''+
                ", profession='" + profession +'\''+
                '}';
    }

}
